import streamlit as st
import pandas as pd
import os
from eda_agents.utils.logger import logger

st.set_page_config(
    page_title="EDA Agents Portal",
    page_icon="🤖",
    layout="wide",
    initial_sidebar_state="expanded",
)

def main():
    st.title("🤖 EDA Agents Portal")
    st.markdown("### Agentic Framework for Data Ingestion & Analysis")

    st.sidebar.title("Navigation")
    app_mode = st.sidebar.selectbox("Choose the mode", ["Home", "Data Ingestion", "Analysis", "Reporting"])

    if app_mode == "Home":
        st.write("Welcome to the EDA Agents Portal. Use the sidebar to navigate.")
        st.info("Upload your data in the 'Data Ingestion' section to get started.")

    elif app_mode == "Data Ingestion":
        st.header("Data Ingestion")
        uploaded_file = st.file_uploader("Upload a file", type=["csv", "txt", "xlsx"])
        
        if uploaded_file is not None:
            try:
                if uploaded_file.name.endswith('.csv'):
                    df = pd.read_csv(uploaded_file)
                elif uploaded_file.name.endswith('.xlsx'):
                    df = pd.read_excel(uploaded_file)
                else:
                    df = pd.read_table(uploaded_file)
                
                st.write(f"Loaded {len(df)} rows and {len(df.columns)} columns.")
                st.dataframe(df.head())
                
                # Save to session state for other modules
                st.session_state['current_dataframe'] = df
                st.success("File uploaded successfully!")
                logger.info(f"File {uploaded_file.name} uploaded successfully.")
                
            except Exception as e:
                st.error(f"Error loading file: {e}")
                logger.error(f"Error loading file: {e}")

    elif app_mode == "Analysis":
        st.header("Exploratory Data Analysis")
        if 'current_dataframe' in st.session_state:
            df = st.session_state['current_dataframe']
            
            st.subheader("Data Overview")
            st.write(df.describe())
            
            st.subheader("Missing Values")
            st.write(df.isnull().sum())
            
            # Future: Integrate Agents here to perform automated analysis
            st.info("Agentic analysis coming soon...")
        else:
            st.warning("Please upload a file in the Data Ingestion section first.")

    elif app_mode == "Reporting":
        st.header("Reports (Future)")
        st.write("This section will contain downloadable reports generated by the agents.")

if __name__ == "__main__":
    main()
